all:
  hosts:
    node1:
      ansible_host: 10.1.111.11
      ip: 10.1.111.11
      access_ip: 10.1.111.11
    node2:
      ansible_host: 10.1.111.12
      ip: 10.1.111.12
      access_ip: 10.1.111.12
    node3:
      ansible_host: 10.1.111.13
      ip: 10.1.111.13
      access_ip: 10.1.111.13
    node4:
      ansible_host: 10.1.111.14
      ip: 10.1.111.14
      access_ip: 10.1.111.14
    node5:
      ansible_host: 10.1.111.15
      ip: 10.1.111.15
      access_ip: 10.1.111.15
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
